[package]
name = "parser_combinator"
version = "0.1.0"
authors = ["James Hagans <jhagans@acm.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "5.1.2"